name: "Custom Action"
description: "Añadir meme al README dependiendo del resultado del test"
inputs:
  frase_positiva:
    description: "Meme de success"
    required: true
  frase_negativa:
    description: "Meme de error"
    required: true
  resultado_tests:
    description: "Resultado del test"
    required: true
runs:
  using: "node16"
  main: "src/dist/index.js"