name: example-workflow
on: 
  push:
   branches:
    - react_app_deploy
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install && npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: build/
  deploy-job:
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - uses: actions/download-artifact@v2
        with: 
          name: my-artifact
      - name: Deploy to salva-designer.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'salva-designer.surge.sh'
          project: '.'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
