name: main-workflow
on: 
  push:
   branches:
    - nodejs_nodeversions_job
jobs:
  linter-execution:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12]
    steps:
      - uses: actions/checkout@v2
      - name: Setting node version
        uses: actions/setup-node@v2
        with: 
          node-version: ${{ matrix.node }}
      - uses: github/super-linter@v4
    env:
      DEFAULT_BRANCH: nodejs_example
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      LINTER_RULES_PATH: /
      JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
      VALIDATE_JAVASCRIPT_ES: true
  test-execution:
    runs-on: ubuntu-latest
    needs: linter-execution
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run jest tests
        run: npm install jest && npm test